lib/laphub_web/router.ex
defmodule LaphubWeb.Router do
  use LaphubWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {LaphubWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", LaphubWeb do
    pipe_through :browser

    get "/", PageController, :index

    post "/account/login", AccountController, :login
    live "/account/login", LoginLive, :login_form
    live "/account/reset", ResetLive, :reset_form

    live "/account/register", RegisterLive, :register_form

    live "/sessions", SessionsLive, :sessions
    live "/teams", TeamsLive, :teams
    live "/teams/new", TeamEditorLive, :team_editor
    live "/teams/:team_id", TeamEditorLive, :team_editor

    live "/sessions/:session_id", SessionLive, :session
    live "/sessions/:session_id/dash/:dash_id", SessionLive, :session

    get "/hls/:session_id/:filename", HlsController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", LaphubWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/", LaphubWeb do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/laphub_web/views/layout_view.ex
defmodule LaphubWeb.LayoutView do
  use LaphubWeb, :view
  # use CatsWeb, :view
  # import Plug.Conn
  # alias CatsWeb.Router.Helpers, as: Routes
  # import CatsWeb.Components.Common
  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}

  alias Laphub.Account.User
  import Plug.Conn
  alias LaphubWeb.Icons

  def is_logged_in?(conn) do
    case get_session(conn, :user) do
      %User{} -> true
      _ -> false
    end
  end

  def user(conn), do: get_session(conn, :user)

  def user_display(conn) do
    case get_session(conn, :user) do
      %User{} = user ->
        user.display_name || user.email

      _ ->
        nil
    end
  end
end

lib/laphub_web/templates/layout/app.html.heex
<main>
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/laphub_web/templates/layout/live.html.heex
<main>
  <% info = Phoenix.Flash.get(@flash, :info) %>
  <% error = Phoenix.Flash.get(@flash, :error) %>
  <%= if info do %>
    <p class="flash alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= Phoenix.Flash.get(@flash, :info) %></p>
  <% end %>
  <%= if error do %>
    <p class="flash alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= Phoenix.Flash.get(@flash, :error) %></p>
  <% end %>
  <%= @inner_content %>
</main>

lib/laphub_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en" data-theme="light">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="csrf-token" content={csrf_token_value()}>
    <%= live_title_tag assigns[:page_title] || "Laphub", suffix: " · Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  </head>
  <body>
    <header>
      <nav>
        <ul>
          <li><%= link "laps", to: "/", class: "only-desktop item" %></li>
          <li><%= live_redirect "Sessions", to: Routes.sessions_path(@conn, :sessions), class: "item" %></li>
          <li><%= live_redirect "Teams", to: Routes.teams_path(@conn, :teams), class: "item" %></li>

          <li>
            <a href="/" class="only-mobile mobile-home">
              <Icons.home />
            </a>
          </li>
        </ul>

        <ul>
          <%= if is_logged_in?(@conn) do %>
            <li>Hello <%= user_display(@conn) %></li>
          <% else %>
            <li><%= live_redirect "sign up", to: Routes.register_path(@conn, :register_form), class: "item" %></li>
            <li><%= live_redirect "log in", to: Routes.login_path(@conn, :login_form), class: "item" %></li>
          <% end %>
        </ul>
      </nav>
    </header>
    <%= @inner_content %>
  </body>
</html>